question_data = [{"category": "Geography",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "Greenland is almost as big as Africa.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Linus Torvalds created Linux and Git.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "easy",
                  "question": "RAM stands for Random Access Memory.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy", "question": "Salt is 100% composed of Sodium.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
                  "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The Lego Group was founded in 1932.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Klingons express emotion in art through opera and poetry.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
